# Generated by Django 5.2.6 on 2025-09-12 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-created_at'], 'permissions': [('can_approve_leaves', 'Puede aprobar ausencias')]},
        ),
    ]
